name: capstone-ZEIT-2020-ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - jupyterlab=2.2.9
  - pandas=1.1.4
  - numpy=1.19.4
  - matplotlib=3.3.2
  - seaborn=0.11.0
  - scikit-learn=0.23.2
  - geopandas=0.8.1
  - imbalanced-learn=0.7.0
  - xgboost=1.2.0
  - descartes=1.1.0